CREATE TABLE `sd_action_result` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_name` varchar(100) DEFAULT NULL COMMENT 'job名',
  `job_group_name` varchar(100) DEFAULT NULL COMMENT '组名',
  `action` varchar(100) DEFAULT NULL COMMENT '动作',
  `action_no` varchar(50) DEFAULT NULL COMMENT '动作编号',
  `ip` varchar(2000) DEFAULT NULL COMMENT '操作IP',
  `cron_expression` varchar(100) DEFAULT NULL COMMENT '时间表达式',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `simple_trigger_json` varchar(200) DEFAULT NULL COMMENT 'simple json字符串',
  `only_run_once` tinyint(4) DEFAULT NULL COMMENT '是否只运行一次',
  `dist_ips` varchar(2000) DEFAULT NULL COMMENT '运行节点IP列表',
  PRIMARY KEY (`id`),
  KEY `index_jobName_jobGroupName` (`job_name`,`job_group_name`)
) ENGINE=InnoDB AUTO_INCREMENT=172 DEFAULT CHARSET=utf8;


CREATE TABLE `sd_job_all_tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_name` varchar(100) DEFAULT NULL COMMENT 'job名称',
  `job_group_name` varchar(100) DEFAULT NULL COMMENT 'job组名',
  `trigger_name` varchar(100) DEFAULT NULL COMMENT 'trigger名称',
  `trigger_group_name` varchar(100) DEFAULT NULL COMMENT 'trigger组名',
  `job_memo` varchar(500) DEFAULT NULL COMMENT 'job介绍',
  `job_time_type` varchar(50) DEFAULT NULL COMMENT 'simple:cron',
  `job_environment_type` varchar(100) DEFAULT NULL COMMENT 'single:distribute',
  `simple_trigger_json` varchar(500) DEFAULT NULL COMMENT 'simple_trigger配置 json方式',
  `cron_expression` varchar(100) DEFAULT NULL COMMENT '时间表达式',
  `only_run_once` tinyint(4) DEFAULT NULL COMMENT '任务只运行一次',
  `target_object` varchar(500) DEFAULT NULL COMMENT '目标对象',
  `target_method` varchar(200) DEFAULT NULL COMMENT '目标方法',
  `arguments` varchar(5000) DEFAULT NULL COMMENT '参数值',
  `dist_ips` varchar(1000) DEFAULT NULL COMMENT '多节点任务IPS',
  `run_status` varchar(45) DEFAULT NULL COMMENT '运行状态',
  `last_action_no` varchar(45) DEFAULT NULL COMMENT '上一次操作编号',
  `last_action_result` varchar(45) DEFAULT NULL COMMENT '上一次操作结果',
  `last_run_time` datetime DEFAULT NULL COMMENT '上一次运行时间',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '记录修改时间',
  `start_delay` int(11) DEFAULT NULL COMMENT '延时毫秒数',
  `repeat_count` int(11) DEFAULT NULL COMMENT '重复执行次数',
  `repeat_interval` int(11) DEFAULT NULL COMMENT '重复时间间隔毫秒',
  `is_dynamic_add` tinyint(4) DEFAULT NULLCOMMENT '是否动态添加',
  PRIMARY KEY (`id`),
  KEY `index_jobName_jobGroupName` (`job_name`,`job_group_name`),
  KEY `index_jobGroupName` (`job_group_name`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;

CREATE TABLE `sd_job_operator_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `operator` varchar(45) DEFAULT NULL COMMENT '操作人',
  `content` longtext COMMENT '操作内容',
  `type` varchar(45) DEFAULT NULL COMMENT '类型：pause resume remove run_at_once add_from_remove_list',
  `job_name` varchar(100) DEFAULT NULL COMMENT 'job名',
  `job_group_name` varchar(100) DEFAULT NULL COMMENT '组名',
  `action_no` varchar(45) DEFAULT NULL COMMENT '动作编号',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `success` tinyint(4) DEFAULT '0' COMMENT '操作是否成功',
  PRIMARY KEY (`id`),
  KEY `index_jobName_jobGroupName` (`job_name`,`job_group_name`),
  KEY `index_actionNo` (`action_no`)
) ENGINE=InnoDB AUTO_INCREMENT=184 DEFAULT CHARSET=utf8;


CREATE TABLE `sd_job_trigger_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_name` varchar(100) DEFAULT NULL COMMENT 'job名',
  `job_group_name` varchar(100) DEFAULT NULL COMMENT 'job所属组',
  `cron_expression` varchar(100) DEFAULT NULL COMMENT '时间表达式',
  `run_memo` longtext  COMMENT '运行信息备注',
  `start_time` bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',
  `end_time` bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',
  `run_status` int(11) DEFAULT NULL COMMENT 'job运行是否成功',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `ip` varchar(50) DEFAULT NULL COMMENT 'IP',
  PRIMARY KEY (`id`),
  KEY `index_jobName_jobGroupName` (`job_name`,`job_group_name`)
) ENGINE=InnoDB AUTO_INCREMENT=10272 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';

CREATE TABLE `sd_job_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(45) NOT NULL COMMENT '用户名',
  `pass_word` varchar(45) NOT NULL COMMENT '密码',
  `role` varchar(45) NOT NULL COMMENT '角色admin tl',
  `group_names` varchar(300) NOT NULL COMMENT '可操作组,逗号分隔',
  `is_delete` int(11) NOT NULL DEFAULT '0' COMMENT '是否删除',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modify_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `index_userName_passWord` (`user_name`,`pass_word`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE sd_job_trigger_log_201501(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201502(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201503(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201504(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201505(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201506(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201507(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201508(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201509(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201510(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201511(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201512(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';

CREATE TABLE sd_job_trigger_log_201601(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201602(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201603(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201604(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201605(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201606(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201607(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201608(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201609(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201610(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201611(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201612(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';

CREATE TABLE sd_job_trigger_log_201701(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201702(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201703(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201704(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201705(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201706(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201707(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201708(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201709(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201710(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201711(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201712(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';


CREATE TABLE sd_job_trigger_log_201801(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201802(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201803(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201804(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201805(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201806(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201807(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201808(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201809(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201810(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201811(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';
CREATE TABLE sd_job_trigger_log_201812(id int(11) NOT NULL AUTO_INCREMENT,job_name varchar(100) DEFAULT NULL COMMENT 'job名', job_group_name varchar(100) DEFAULT NULL COMMENT 'job所属组',cron_expression varchar(100) DEFAULT NULL COMMENT '时间表达式',  run_memo longtext COMMENT '运行信息备注',  start_time bigint(20) DEFAULT NULL COMMENT '方法运行开始时间',  end_time bigint(20) DEFAULT NULL COMMENT '方法运行结束时间',  run_status int(11) DEFAULT NULL COMMENT 'job运行是否成功',  create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',  ip varchar(50) DEFAULT NULL COMMENT 'IP',  PRIMARY KEY (id),  KEY index_jobName_jobGroupName (job_name,job_group_name)) ENGINE=InnoDB AUTO_INCREMENT=10598 DEFAULT CHARSET=utf8 COMMENT='任务运行日志表';

